train: ./dataset/images/train  # relative path to train images
val: ./dataset/images/val  # relative path to val images
test: ./dataset/images/public_test  # relative path to public test images

# Classes
# Please don't change

# bao gom background
num_classes: 4  # number of classes
# names: ['0', '1', '2']
names: ['no_mask', 'mask', 'incorrect_mask']