data_config: "./configs/data_config.yaml"
model_type: fasterrcnn_resnet50_fpn
model_name: faster_rcnn_1
logging_file: "./test_folder/logging.txt"

do_train: True
do_predict: False

batch_size: 10

train_args:
    checkpoint: 8040
    load_optimizer: True
    load_lr_scheduler: True
    lr: 5e-4
    strategy: epoch # step or epoch
    # n_steps: 100
    n_epochs: 30
    lr_steps: 500
    steps_per_epoch: null # for augmentation in strategy epoch
    logging_dir: "/content/gdrive/MyDrive/cv/fasterrcnn"
    device: cuda
    eval_interval: null
    save_folder: "/content/gdrive/MyDrive/cv/fasterrcnn"
    # save_folder: test_folder
    save_strategy: epoch # step or epoch 
    save_interval: 2
    # start_epoch: 2